### ISSUE TITLE
conda-forge version 1.1.5

### ISSUE THREAD

**Issue by JoeZiminski** [damonlynch/showinfilemanager#10]
Currently the conda-forge build for the new version is failing,  with error:

` ModuleNotFoundError: build_manpages`

I think this is because the `argparse-manpage` conda aversion is out of date. I have raised [an issue](https://github.com/praiskup/argparse-manpage/issues/108). Just creating this issue to keep a record.

**Comment by damonlynch** [comment]
It looks like Conda does have the latest version of `argparse-manpage`. So the problem must lie elsewhere. 

I was able to build an [Ubuntu package](https://launchpad.net/~dlynch3/+archive/ubuntu/rapid-photo-downloader-testing) of 1.1.5 (using the Ubuntu package builders), as well as the wheel & distribution tarball (using `python -m build`). That indicates the build should be possible.

**Comment by JoeZiminski** [comment]
Hey @damonlynch in the end the version was fine and was nothing to do with the conda install, instead the requirement needed to be specified in a different place in the `meta.yaml` I had written for conda. All sorted now, thanks!

**Comment by damonlynch** [comment]
Hi @JoeZiminski I just want to let you know that the next of release of Show in File Manager has an improved build system, that will require some changes in your package. I have added some [draft release notes](https://github.com/damonlynch/showinfilemanager/blob/main/RELEASE_NOTES.md). If you have any questions or concerns at all, please don't hesitate to ask. I'm sorry for any inconvenience this might cause you. Hopefully the changes required for packaging the next version will be minimal.
