### ISSUE TITLE
Upload to conda-forge

### ISSUE THREAD

**Issue by JoeZiminski** [damonlynch/showinfilemanager#8]
Thanks for building this great package, we have found it very useful!

We want to add a package that depends on `show-in-file-manager` to conda-forge, requiring this package also be added. It would be great to get this package on `conda-forge`, I'd be happy to build the meta file for conda and raise the PR on `staged-recipes` if useful.

Cheers,
Joe

**Comment by damonlynch** [comment]
Hi Joe,

I'm glad you find the program useful. I'm afraid I have zero experience with conda. Is there anything that you need me to do, or is this issue to let me know that it is now in conda?

Damon

**Comment by JoeZiminski** [comment]
Hi @damonlynch, nope I can open the PR on conda-forge recipes, I think all they need is for you to respond indicating you are happy to be listed as a maintainer, I can ping you at this stage and you can take a look. This issue was just to run it by you before proceeding, thanks I will keep you updated!

**Comment by JoeZiminski** [comment]
Hi @damonlynch, the package is now on conda forge, cheers!
